# From https://github.com/felddy/foundryvtt-docker
services:
  foundry:
    image: ghcr.io/felddy/foundryvtt:latest
    hostname: foundry-vtt # used for validating the software licence, do not change it
    volumes:
      - type: bind
        source: ./foundry
        target: /data
    environment:
      - FOUNDRY_TELEMETRY=true
      - CONTAINER_PRESERVE_CONFIG=true
    env_file:
      - .env
    ports:
      - target: 30000
        published: 30000
        protocol: tcp